/**
 * Normalized Result Artifact Payload Contract
 *
 * The conceptual payload shape that downstream consumers of an assessment
 * result SHOULD align to. Today the repo has four conceptual consumers:
 *
 *   1. ResultsScreen  — on-page render (3-page flow)
 *   2. Email summary  — composed by n8n from the email-capture webhook event
 *   3. PDF download   — generated by /api/assessments/results-pdf (pdfkit)
 *   4. Webhook event  — webhook_outbox row posted to n8n on email-capture
 *
 * Each consumer currently builds its own shape from `SubmissionData` + the
 * resolved results pack. This module does NOT rewrite those consumers (that
 * would risk changing Gut Check runtime behavior, which Packet I forbids).
 * Instead it:
 *
 *   - defines the canonical `ResultArtifactPayload` type,
 *   - exposes a pure `buildResultArtifactPayload` helper that produces it from
 *     a submission + resolved results content,
 *   - documents, per field, which consumer currently uses it (coverage map) so
 *     a future packet can close gaps without guessing.
 *
 * This is the contract layer only. Consumers are not migrated in this packet.
 */

import type { SubmissionData } from '@/lib/assessments/results/types';
import type { AssessmentType } from '@/lib/assessmentTypes';

// ---------------------------------------------------------------------------
// Canonical payload
// ---------------------------------------------------------------------------

/** One recommended focus area / next step surfaced across screen + email + PDF. */
export interface ResultRecommendation {
  title: string;
  bullets: string[];
}

/**
 * The normalized artifact payload. Every field is nullable so a consumer can
 * degrade gracefully when a results pack lacks Flow v2 content (legacy packs
 * only populate the legacy fields).
 */
export interface ResultArtifactPayload {
  /** Stable assessment type (gut-check). */
  assessmentType: AssessmentType;
  /** Assessment version that produced this result (drives scoring engine). */
  assessmentVersion: number;
  /** Submission row id — the shared key across screen / email / PDF / webhook. */
  submissionId: string;
  /** Session id (for analytics joins). */
  sessionId: string;
  /** Computed result level id (primary_avatar on the submission row). */
  levelId: string;
  /** Human-readable level label from the results pack. */
  levelLabel: string | null;
  /** Secondary modifier (e.g. high_responsiveness), if the engine emitted one. */
  secondaryModifier: string | null;
  /** Engine confidence label (high / moderate / low). */
  confidence: 'high' | 'moderate' | 'low' | null;
  /** Axis→normalized score map, if available. */
  normalizedScoreMap: Record<string, number>;
  /** Captured email, if the user submitted one via email-capture. */
  email: string | null;
  /** Whether the submission has been claimed / attached to an account. */
  claimed: boolean;
  /** Claim token for guest submissions (only present before claim). */
  claimToken: string | null;
  /** Page 1 content reference (headline + snapshot). */
  page1: {
    headline: string | null;
    snapshotBullets: string[];
  } | null;
  /** Page 2 content reference (steps + video CTA). */
  page2: {
    headline: string | null;
    stepBullets: string[];
    videoAssetUrl: string | null;
  } | null;
  /** Page 3 content reference (mechanism + method CTA). */
  page3: {
    problemHeadline: string | null;
    methodCtaLabel: string | null;
    methodCtaUrl: string | null;
  } | null;
  /** Recommended focus areas / next steps. */
  recommendations: ResultRecommendation[];
  /** Channel flags as declared by the results pack (metadata only — NOT enforced). */
  channels: {
    web: boolean;
    email: boolean;
    pdf: boolean;
  };
  /** Where the result copy came from. */
  copySource: 'cms-results-pack' | 'file-results-pack' | 'hardcoded' | 'unknown';
}

// ---------------------------------------------------------------------------
// Builder
// ---------------------------------------------------------------------------

/**
 * Input for `buildResultArtifactPayload`. The caller supplies the submission
 * row plus the resolved results content (Flow v2 pages or legacy fields). The
 * helper stays pure — no API calls, no scoring.
 */
export interface ResultArtifactPayloadInput {
  submission: SubmissionData;
  levelLabel?: string | null;
  secondaryModifier?: string | null;
  confidence?: 'high' | 'moderate' | 'low' | null;
  /** Flow v2 page content, if resolved. */
  flow?: {
    page1?: {
      headline?: string;
      snapshotBullets?: string[];
    } | null;
    page2?: {
      headline?: string;
      stepBullets?: string[];
      videoAssetUrl?: string | null;
    } | null;
    page3?: {
      problemHeadline?: string;
      methodCtaLabel?: string;
      methodCtaUrl?: string;
    } | null;
  } | null;
  /** Legacy results pack fields, used when Flow v2 is absent. */
  legacy?: {
    summary?: string;
    keyPatterns?: string[];
    firstFocusAreas?: string[];
  } | null;
  /** Channel flags from the results pack (defaults: web true, email true, pdf false). */
  channels?: {
    web?: boolean;
    email?: boolean;
    pdf?: boolean;
  };
  /** Where the result copy came from. */
  copySource?: ResultArtifactPayload['copySource'];
}

/**
 * Build a normalized `ResultArtifactPayload` from a submission + resolved
 * results content. Pure and defensive: missing content degrades to null/empty
 * rather than throwing.
 */
export function buildResultArtifactPayload(
  input: ResultArtifactPayloadInput
): ResultArtifactPayload {
  const { submission, flow, legacy, channels, copySource } = input;

  const snapshotBullets = flow?.page1?.snapshotBullets ?? legacy?.keyPatterns ?? [];
  const stepBullets = flow?.page2?.stepBullets ?? legacy?.firstFocusAreas ?? [];

  const recommendations: ResultRecommendation[] = [];
  if (legacy?.firstFocusAreas && legacy.firstFocusAreas.length > 0) {
    recommendations.push({
      title: 'First focus areas',
      bullets: legacy.firstFocusAreas,
    });
  }
  if (flow?.page2?.stepBullets && flow.page2.stepBullets.length > 0 && !recommendations.length) {
    recommendations.push({
      title: 'Next steps',
      bullets: flow.page2.stepBullets,
    });
  }

  return {
    assessmentType: submission.assessment_type as AssessmentType,
    assessmentVersion: submission.assessment_version,
    submissionId: submission.id,
    sessionId: submission.session_id,
    levelId: submission.primary_avatar,
    levelLabel: input.levelLabel ?? null,
    secondaryModifier: input.secondaryModifier ?? null,
    confidence: input.confidence ?? null,
    normalizedScoreMap: submission.normalized_score_map ?? {},
    email: submission.email ?? null,
    claimed: !!submission.user_id,
    claimToken:
      (submission.metadata as { claimToken?: string } | null)?.claimToken ?? null,
    page1: flow?.page1
      ? {
          headline: flow.page1.headline ?? null,
          snapshotBullets,
        }
      : legacy?.summary
      ? { headline: legacy.summary, snapshotBullets }
      : null,
    page2: flow?.page2
      ? {
          headline: flow.page2.headline ?? null,
          stepBullets,
          videoAssetUrl: flow.page2.videoAssetUrl ?? null,
        }
      : null,
    page3: flow?.page3
      ? {
          problemHeadline: flow.page3.problemHeadline ?? null,
          methodCtaLabel: flow.page3.methodCtaLabel ?? null,
          methodCtaUrl: flow.page3.methodCtaUrl ?? null,
        }
      : null,
    recommendations,
    channels: {
      web: channels?.web ?? true,
      email: channels?.email ?? true,
      pdf: channels?.pdf ?? false,
    },
    copySource: copySource ?? 'unknown',
  };
}

// ---------------------------------------------------------------------------
// Coverage map (documentation-as-code)
// ---------------------------------------------------------------------------

/** Which downstream consumer currently consumes each payload field. */
export interface PayloadFieldCoverage {
  field: keyof ResultArtifactPayload;
  screen: boolean;
  email: boolean;
  pdf: boolean;
  webhook: boolean;
  notes?: string;
}

/**
 * Static coverage map. This documents the CURRENT state of consumer alignment,
 * not the desired state. It is intentionally honest: a field marked false on
 * `email` means the n8n email workflow does not receive that field today.
 *
 * Used by the admin hub to show alignment gaps. A future packet can use this
 * same map to plan consumer migration.
 */
export const RESULT_PAYLOAD_COVERAGE: PayloadFieldCoverage[] = [
  { field: 'assessmentType', screen: true, email: true, pdf: true, webhook: true },
  { field: 'assessmentVersion', screen: true, email: true, pdf: true, webhook: true },
  { field: 'submissionId', screen: true, email: true, pdf: true, webhook: true },
  { field: 'sessionId', screen: true, email: false, pdf: false, webhook: true },
  { field: 'levelId', screen: true, email: true, pdf: true, webhook: true, notes: 'primary_avatar on submission row.' },
  { field: 'levelLabel', screen: true, email: true, pdf: true, webhook: false },
  { field: 'secondaryModifier', screen: true, email: false, pdf: false, webhook: true },
  { field: 'confidence', screen: true, email: false, pdf: false, webhook: true },
  { field: 'normalizedScoreMap', screen: false, email: false, pdf: false, webhook: true, notes: 'Webhook receives score_map; screen does not render raw scores.' },
  { field: 'email', screen: false, email: true, pdf: false, webhook: true, notes: 'Email is the destination address, not screen content.' },
  { field: 'claimed', screen: true, email: false, pdf: false, webhook: false },
  { field: 'claimToken', screen: true, email: false, pdf: false, webhook: false, notes: 'Used by ResultsScreen claim CTA only.' },
  { field: 'page1', screen: true, email: true, pdf: true, webhook: false },
  { field: 'page2', screen: true, email: true, pdf: true, webhook: false },
  { field: 'page3', screen: true, email: false, pdf: true, webhook: false, notes: 'Email typically excludes the method CTA page.' },
  { field: 'recommendations', screen: true, email: true, pdf: true, webhook: false },
  { field: 'channels', screen: false, email: false, pdf: false, webhook: false, notes: 'Metadata only; not enforced by any consumer today.' },
  { field: 'copySource', screen: false, email: false, pdf: false, webhook: false, notes: 'Diagnostic only.' },
];

/** Count how many consumers consume each field — used by the admin coverage view. */
export function payloadCoverageSummary() {
  const total = RESULT_PAYLOAD_COVERAGE.length;
  let fullyAligned = 0;
  let partial = 0;
  let unused = 0;
  for (const row of RESULT_PAYLOAD_COVERAGE) {
    const used = [row.screen, row.email, row.pdf, row.webhook].filter(Boolean).length;
    if (used === 4) fullyAligned++;
    else if (used === 0) unused++;
    else partial++;
  }
  return { total, fullyAligned, partial, unused };
}
