import type { ProgramDeliveryModuleDefinition } from './deliveryModuleTypes';
import { APP_ROUTES } from '@/lib/routes/appRoutes';

const BASELINE_SLUG = 'baseline';

const baseRoadmap = [
  {
    key: 'prep',
    label: 'Prep',
    range: 'Day 0',
    description: 'Arrive, map meals, and get the pantry ready.',
    dayStart: 0,
    dayEnd: 0,
  },
  {
    key: 'week-1',
    label: 'Week 1',
    range: 'Days 1-7',
    description: 'Run the baseline rhythm with minimal changes.',
    dayStart: 1,
    dayEnd: 6,
  },
  {
    key: 'day-7',
    label: 'Day 7 check-in',
    range: 'Day 7',
    description: 'Capture the first week of signals.',
    dayStart: 7,
    dayEnd: 7,
  },
  {
    key: 'week-2',
    label: 'Week 2',
    range: 'Days 8-14',
    description: 'Keep the baseline steady and observe patterns.',
    dayStart: 8,
    dayEnd: 13,
  },
  {
    key: 'day-14',
    label: 'Day 14 check-in',
    range: 'Day 14',
    description: 'Review the second weekly signal set.',
    dayStart: 14,
    dayEnd: 14,
  },
  {
    key: 'week-3',
    label: 'Week 3',
    range: 'Days 15-21',
    description: 'Finish the baseline window before recommendations.',
    dayStart: 15,
    dayEnd: 20,
  },
  {
    key: 'day-21',
    label: 'Day 21 check-in / recommendation',
    range: 'Day 21',
    description: 'Complete the final check-in and prepare the next step.',
    dayStart: 21,
    dayEnd: 21,
  },
] as const;

export const BASELINE_PREP_DELIVERY_MODULES: ProgramDeliveryModuleDefinition[] = [
  {
    id: 'baseline-prep-overview',
    programSlug: BASELINE_SLUG,
    moduleType: 'prep',
    groupId: 'baseline-prep',
    groupTitle: 'Baseline preparation',
    eyebrow: 'Baseline preparation',
    title: 'Set up your Baseline',
    body: 'Use these modules to arrive, map your repeatable meals, and prepare your pantry before day 1.',
    statusVisibility: ['pre_start', 'active'],
    statusCopy: {
      active: {
        eyebrow: 'Day 0 reference',
        title: 'Prep modules remain available',
        body: 'Return to these setup steps any time while Baseline is active.',
      },
    },
    blocks: [
      {
        type: 'metrics',
        metrics: ['selected_start', 'current_day', 'capacity', 'content_progress'],
      },
    ],
  },
  {
    id: 'baseline-arrive',
    programSlug: BASELINE_SLUG,
    moduleType: 'prep',
    groupId: 'baseline-prep',
    eyebrow: 'Orientation / Arrive',
    title: 'Arrive before the program starts',
    body: 'This area will hold the Day 0 orientation, including the future audio or video intro for the Baseline setup.',
    statusVisibility: ['pre_start', 'active'],
    blocks: [
      {
        type: 'notice',
        eyebrow: 'Future media area',
        title: 'Audio or video guidance will live here.',
        body: 'For now, use this step as the arrival point before building the rest of your Day 0 setup.',
        tone: 'muted',
      },
    ],
  },
  {
    id: 'baseline-meal-map',
    programSlug: BASELINE_SLUG,
    moduleType: 'prep',
    groupId: 'baseline-prep',
    eyebrow: 'Build Your Meal Map',
    title: 'Turn preparation into a simple map',
    body: 'The meal map connects the setup work: create baseline meal placeholders first, then prepare the pantry around those choices.',
    statusVisibility: ['pre_start', 'active'],
    blocks: [
      {
        type: 'cards',
        cards: [
          {
            title: 'Create Meals',
            body: 'Import a recipe draft or paste a meal idea into the existing Plans review flow.',
          },
          {
            title: 'Prepare Pantry',
            body: 'Dedicated pantry readiness is not routed yet. Grocery work still belongs inside active Plans.',
          },
        ],
      },
    ],
  },
  {
    id: 'baseline-create-meals',
    programSlug: BASELINE_SLUG,
    moduleType: 'prep',
    groupId: 'baseline-prep',
    eyebrow: 'Create Meals',
    title: 'Create baseline meal shells',
    body: 'Use the existing Plans import flow to turn a recipe, link, or social video evidence into a reviewable draft. This does not create new Baseline meal logic.',
    statusVisibility: ['pre_start', 'active'],
    cta: {
      label: 'Open recipe import',
      href: APP_ROUTES.planImportNew,
      microcopy:
        'This routes to the current Plans import workflow, where drafts can be reviewed before they become saved meals or planned meals.',
    },
  },
  {
    id: 'baseline-prepare-pantry',
    programSlug: BASELINE_SLUG,
    moduleType: 'prep',
    groupId: 'baseline-prep',
    eyebrow: 'Prepare Pantry',
    title: 'Prepare pantry and grocery readiness',
    body: 'A dedicated pantry readiness route does not exist yet. Grocery generation remains available from Plans once an active plan exists.',
    statusVisibility: ['pre_start', 'active'],
    cta: {
      label: 'Pantry readiness coming soon',
      disabled: true,
      microcopy:
        'No safe standalone pantry destination was found, and the grocery route requires an existing plan id.',
    },
  },
  {
    id: 'baseline-roadmap',
    programSlug: BASELINE_SLUG,
    moduleType: 'roadmap',
    groupId: 'baseline-prep',
    eyebrow: 'Program Roadmap',
    title: 'Baseline sequence',
    body: 'Baseline runs as a three-week observation sequence with weekly check-ins and a final recommendation checkpoint.',
    statusVisibility: ['pre_start', 'active'],
    blocks: [{ type: 'roadmap', items: [...baseRoadmap] }],
  },
];

export const BASELINE_WEEK_DELIVERY_MODULES: ProgramDeliveryModuleDefinition[] = [
  {
    id: 'baseline-week-1-focus',
    programSlug: BASELINE_SLUG,
    moduleType: 'week',
    groupId: 'baseline-week-1',
    groupTitle: 'Week 1 in Baseline',
    eyebrow: 'Week 1 focus',
    title: 'Eating Rhythm',
    body: 'This week is about finding a steady rhythm you can repeat. My body is not the problem; the work is to listen, nourish, and make the next meal easier to return to.',
    dayStart: 1,
    dayEnd: 7,
    statusVisibility: ['active'],
    blocks: [
      {
        type: 'notice',
        title: 'Day {{current_day}}: consistency over correctness',
        body: 'You are not trying to perfect your meals. You are collecting information about what helps you feel steady.',
        tone: 'emerald',
      },
    ],
  },
  {
    id: 'baseline-week-1-practice',
    programSlug: BASELINE_SLUG,
    moduleType: 'practice_card',
    groupId: 'baseline-week-1',
    eyebrow: "Today's practice",
    title: 'Nourish before you optimize',
    body: 'Choose the next simple meal or snack that helps today feel more steady. Repeat meals when repetition makes the day easier.',
    dayStart: 1,
    dayEnd: 7,
    statusVisibility: ['active'],
    blocks: [
      {
        type: 'list',
        items: [
          'Eat within 60-90 minutes of waking when you can.',
          'Aim to eat every 3-4 hours while you are awake.',
          'Include protein, carbs, and fat at meals.',
          'Repeat breakfast or lunch if that lowers friction.',
        ],
      },
    ],
  },
  {
    id: 'baseline-week-1-guide',
    programSlug: BASELINE_SLUG,
    moduleType: 'guide',
    groupId: 'baseline-week-1',
    eyebrow: 'Eating rhythm guide',
    title: 'Make repeatable meals easier to find',
    body: 'A repeatable meal is not a rule. It is a useful option you can return to when the day is full.',
    dayStart: 1,
    dayEnd: 7,
    statusVisibility: ['active'],
    blocks: [
      {
        type: 'cards',
        cards: [
          {
            title: 'Timing',
            body: 'Notice whether earlier nourishment changes hunger, energy, or cravings later.',
          },
          {
            title: 'Balance',
            body: 'Protein, carbs, and fat can make meals feel more complete without making them complicated.',
          },
          {
            title: 'Repetition',
            body: 'Repeating a meal can create steadiness while you learn your Baseline signals.',
          },
        ],
      },
    ],
  },
  {
    id: 'baseline-week-1-capacity',
    programSlug: BASELINE_SLUG,
    moduleType: 'capacity_support',
    groupId: 'baseline-week-1',
    eyebrow: 'Steady capacity',
    title: 'Build a rhythm you can repeat',
    body: 'Keep meals simple enough to repeat while you observe timing, energy, and hunger patterns.',
    dayStart: 1,
    dayEnd: 7,
    statusVisibility: ['active'],
    capacityVariants: {
      low: {
        eyebrow: 'Low capacity',
        title: 'Keep the rhythm very small',
        body: 'Use the smallest repeatable version of the practice. If energy feels low, prioritize timing over variety.',
        practice:
          'Choose one familiar breakfast or lunch and repeat it as needed.',
      },
      steady: {
        eyebrow: 'Steady capacity',
        title: 'Build a rhythm you can repeat',
        body: 'Keep meals simple enough to repeat while you observe timing, energy, and hunger patterns.',
        practice:
          'Pick a repeatable breakfast and lunch rhythm for the next few days.',
      },
      high: {
        eyebrow: 'High capacity',
        title: 'Add steadiness without adding pressure',
        body: 'You can prepare a little more, but the aim is still repeatable rhythm, not a stricter plan.',
        practice:
          'Set up two repeatable meal options and notice which one feels easiest to return to.',
      },
    },
  },
  {
    id: 'baseline-day-7-checkin',
    programSlug: BASELINE_SLUG,
    moduleType: 'checkin_prompt',
    groupId: 'baseline-week-1',
    eyebrow: 'Day 7 check-in',
    title: 'Your first check-in is ready',
    body: 'This is information, not a test. Use the check-in below to capture what you noticed this week.',
    dayStart: 7,
    dayEnd: 7,
    statusVisibility: ['active'],
    showWhen: 'checkin_due',
    cta: {
      label: 'Go to Day 7 check-in',
      anchorKey: 'checkin',
      tone: 'emerald',
    },
  },
  {
    id: 'baseline-day-7-checkin-handled',
    programSlug: BASELINE_SLUG,
    moduleType: 'checkin_prompt',
    groupId: 'baseline-week-1',
    eyebrow: 'Day 7 check-in',
    title: 'Day 7 check-in',
    body: 'When the Day 7 check-in has been handled, keep using this week as information for what feels repeatable.',
    dayStart: 7,
    dayEnd: 7,
    statusVisibility: ['active'],
    showWhen: 'checkin_not_due',
    cta: {
      label: 'No action needed',
      disabled: true,
      microcopy: 'No action is needed here right now.',
    },
  },
  {
    id: 'baseline-week-2-focus',
    programSlug: BASELINE_SLUG,
    moduleType: 'week',
    groupId: 'baseline-week-2',
    groupTitle: 'Week 2 in Baseline',
    eyebrow: 'Week 2 focus',
    title: 'Digestion & Recovery Support',
    body: 'This week keeps the rhythm steady and adds calm around meals. Your body responds to how you eat, not just what you eat.',
    dayStart: 8,
    dayEnd: 14,
    statusVisibility: ['active'],
    blocks: [
      {
        type: 'notice',
        title: 'Day {{current_day}}: pace, warmth, recovery, and rhythm',
        body: 'If digestion feels off, slow down before changing foods.',
        tone: 'emerald',
      },
    ],
  },
  {
    id: 'baseline-week-2-practice',
    programSlug: BASELINE_SLUG,
    moduleType: 'practice_card',
    groupId: 'baseline-week-2',
    eyebrow: "Today's practice",
    title: 'Slow down before you switch foods',
    body: 'Use the same low-pressure Baseline rhythm, with more attention to pace and recovery cues around meals.',
    dayStart: 8,
    dayEnd: 14,
    statusVisibility: ['active'],
    blocks: [
      {
        type: 'list',
        items: [
          'Slow the first few bites of a meal.',
          'Eat seated when possible.',
          'Choose warm or simple meals when digestion feels off.',
          'Keep meal rhythm steady before changing the menu.',
        ],
      },
    ],
  },
  {
    id: 'baseline-week-2-guide',
    programSlug: BASELINE_SLUG,
    moduleType: 'guide',
    groupId: 'baseline-week-2',
    eyebrow: 'Digestion & recovery guide',
    title: 'Support calm without making stricter rules',
    body: 'Digestion and recovery often respond to the conditions around eating. Treat this as information, not a test.',
    dayStart: 8,
    dayEnd: 14,
    statusVisibility: ['active'],
    blocks: [
      {
        type: 'cards',
        cards: [
          {
            title: 'Pace',
            body: 'Start slower and notice whether the meal feels easier to receive.',
          },
          {
            title: 'Warmth',
            body: 'Warm or simple meals can be useful options when digestion feels variable.',
          },
          {
            title: 'Recovery',
            body: 'A consistent wake time or wind-down cue can support the rhythm around meals.',
          },
        ],
      },
    ],
  },
  {
    id: 'baseline-week-2-capacity',
    programSlug: BASELINE_SLUG,
    moduleType: 'capacity_support',
    groupId: 'baseline-week-2',
    eyebrow: 'Steady capacity',
    title: 'Support calm digestion with rhythm',
    body: 'Keep meals seated when possible, use warm or easy meals when useful, and keep one wake or wind-down cue consistent.',
    dayStart: 8,
    dayEnd: 14,
    statusVisibility: ['active'],
    capacityVariants: {
      low: {
        eyebrow: 'Low capacity',
        title: 'Choose one gentle transition',
        body: 'No overhaul is needed. Pick one meal transition and slow the first few bites before changing foods.',
        practice:
          'At one meal today, sit down if possible and take the first few bites slowly.',
      },
      steady: {
        eyebrow: 'Steady capacity',
        title: 'Support calm digestion with rhythm',
        body: 'Keep meals seated when possible, use warm or easy meals when useful, and keep one wake or wind-down cue consistent.',
        practice:
          'Pair a steady meal rhythm with one calm recovery cue today.',
      },
      high: {
        eyebrow: 'High capacity',
        title: 'Add one recovery anchor',
        body: 'If you have more room, add a repeatable recovery cue without turning it into stricter rules.',
        practice:
          'Choose a simple wind-down cue or warm meal anchor you can repeat this week.',
      },
    },
  },
  {
    id: 'baseline-day-14-checkin',
    programSlug: BASELINE_SLUG,
    moduleType: 'checkin_prompt',
    groupId: 'baseline-week-2',
    eyebrow: 'Day 14 check-in',
    title: 'Your Week 2 check-in is ready',
    body: 'This is information, not a test. Use the check-in below to capture how pace, rhythm, and recovery felt this week.',
    dayStart: 14,
    dayEnd: 14,
    statusVisibility: ['active'],
    showWhen: 'checkin_due',
    cta: {
      label: 'Go to Day 14 check-in',
      anchorKey: 'checkin',
      tone: 'emerald',
    },
  },
  {
    id: 'baseline-day-14-checkin-handled',
    programSlug: BASELINE_SLUG,
    moduleType: 'checkin_prompt',
    groupId: 'baseline-week-2',
    eyebrow: 'Day 14 check-in',
    title: 'Day 14 check-in',
    body: 'When the Day 14 check-in has been handled, keep using this week as information for what supports steadiness.',
    dayStart: 14,
    dayEnd: 14,
    statusVisibility: ['active'],
    showWhen: 'checkin_not_due',
    cta: {
      label: 'No action needed',
      disabled: true,
      microcopy: 'No action is needed here right now.',
    },
  },
  {
    id: 'baseline-week-3-focus',
    programSlug: BASELINE_SLUG,
    moduleType: 'week',
    groupId: 'baseline-week-3',
    groupTitle: 'Week 3 in Baseline',
    eyebrow: 'Week 3 focus',
    title: 'Real-Life Flexibility',
    body: 'This week is about returning to rhythm after disruption and noticing what helped. Flexibility is part of the process, never a setback.',
    dayStart: 15,
    dayEnd: 21,
    statusVisibility: ['active'],
    blocks: [
      {
        type: 'notice',
        title: 'Day {{current_day}}: continue and reinforce',
        body: 'If things feel messy, return to your most reliable meal.',
        tone: 'emerald',
      },
    ],
  },
  {
    id: 'baseline-week-3-practice',
    programSlug: BASELINE_SLUG,
    moduleType: 'practice_card',
    groupId: 'baseline-week-3',
    eyebrow: "Today's practice",
    title: 'Return to the anchor that worked',
    body: 'Choose one steady action that helps you return to rhythm. You do not need to fix the whole week at once.',
    dayStart: 15,
    dayEnd: 21,
    statusVisibility: ['active'],
    blocks: [
      {
        type: 'list',
        items: [
          'Repeat the most reliable meal from Baseline so far.',
          'Return to rhythm after disruption without judgment.',
          'Observe patterns before choosing another change.',
          'Choose one adjustment to continue or reinforce.',
        ],
      },
    ],
  },
  {
    id: 'baseline-week-3-guide',
    programSlug: BASELINE_SLUG,
    moduleType: 'guide',
    groupId: 'baseline-week-3',
    eyebrow: 'Real-life flexibility guide',
    title: 'Make recovery part of the rhythm',
    body: 'Baseline is not asking for a perfect week. It is helping you see which anchors make real life easier to return from.',
    dayStart: 15,
    dayEnd: 21,
    statusVisibility: ['active'],
    blocks: [
      {
        type: 'cards',
        cards: [
          {
            title: 'Return',
            body: 'Use a reliable meal or timing cue as the first move back into rhythm.',
          },
          {
            title: 'Observe',
            body: 'Notice patterns without turning them into a judgment about your body.',
          },
          {
            title: 'Maintain',
            body: 'Choose maintenance anchors that feel repeatable after Baseline.',
          },
        ],
      },
    ],
  },
  {
    id: 'baseline-week-3-capacity',
    programSlug: BASELINE_SLUG,
    moduleType: 'capacity_support',
    groupId: 'baseline-week-3',
    eyebrow: 'Steady capacity',
    title: 'Notice what helped most',
    body: 'Use this week to identify the meal or rhythm that helped you return to steadiness most often.',
    dayStart: 15,
    dayEnd: 21,
    statusVisibility: ['active'],
    capacityVariants: {
      low: {
        eyebrow: 'Low capacity',
        title: 'Return to one reliable anchor',
        body: 'If things feel messy, return to one reliable meal or one rhythm anchor. That is enough for today.',
        practice:
          'Choose the most reliable meal or timing anchor and repeat that before adding anything new.',
      },
      steady: {
        eyebrow: 'Steady capacity',
        title: 'Notice what helped most',
        body: 'Use this week to identify the meal or rhythm that helped you return to steadiness most often.',
        practice:
          'Pick one adjustment to carry forward and one reliable meal to repeat.',
      },
      high: {
        eyebrow: 'High capacity',
        title: 'Choose maintenance anchors, not new rules',
        body: 'If you have more room, choose one or two anchors you want to maintain without making Baseline stricter.',
        practice:
          'Name 1-2 meal or rhythm anchors that helped most and keep them simple.',
      },
    },
  },
  {
    id: 'baseline-day-21-checkin',
    programSlug: BASELINE_SLUG,
    moduleType: 'checkin_prompt',
    groupId: 'baseline-week-3',
    eyebrow: 'Day 21 check-in / recommendation',
    title: 'Your final Baseline check-in is ready',
    body: 'This is information, not a test. Use the check-in below to complete the Baseline signal set.',
    dayStart: 21,
    dayEnd: 21,
    statusVisibility: ['active'],
    showWhen: 'checkin_due',
    cta: {
      label: 'Go to Day 21 check-in',
      anchorKey: 'checkin',
      tone: 'emerald',
    },
  },
  {
    id: 'baseline-day-21-transition',
    programSlug: BASELINE_SLUG,
    moduleType: 'recommendation_prompt',
    groupId: 'baseline-week-3',
    eyebrow: 'Day 21 check-in / recommendation',
    title: 'Day 21 transition',
    body: 'When Day 21 is handled, Fine Diet will prepare a conservative next-step review below.',
    dayStart: 21,
    dayEnd: 21,
    statusVisibility: ['active'],
    showWhen: ['checkin_not_due', 'day21_not_handled'],
    cta: {
      label: 'No action needed',
      disabled: true,
      microcopy: 'No action is needed here right now.',
    },
  },
  {
    id: 'baseline-day-21-recommendation',
    programSlug: BASELINE_SLUG,
    moduleType: 'recommendation_prompt',
    groupId: 'baseline-week-3',
    eyebrow: 'Day 21 check-in / recommendation',
    title: 'Your next-step review is ready',
    body: 'Your Day 21 check-in is handled. Review the recommendation section below when you are ready.',
    dayStart: 21,
    dayEnd: 21,
    statusVisibility: ['active'],
    showWhen: 'day21_handled',
    cta: {
      label: 'Review recommendation',
      anchorKey: 'recommendation',
      tone: 'brand',
    },
  },
];
