/**
 * GET /api/journal/plans/pantry/readiness
 *
 * Packet C — Pantry Readiness Summary. Returns a DERIVED planning-context
 * view composed read-only from the caller's active plan, active grocery list,
 * and pantry_on_hand_items. No readiness state is persisted and no grocery
 * list is generated by this endpoint.
 *
 * Auth: self-only reads. personId is derived from the session.
 *
 * Response 200:
 *   { readiness: PantryReadinessSummary }
 */

import type { NextApiRequest, NextApiResponse } from 'next';
import { requireJournalAccess } from '@/lib/access/requireJournalAccess';
import { getPantryReadiness } from '@/lib/plans/pantryReadinessService';

export default async function handler(req: NextApiRequest, res: NextApiResponse) {
  if (req.method !== 'GET') {
    res.setHeader('Allow', ['GET']);
    return res.status(405).json({ error: `Method ${req.method} not allowed` });
  }

  try {
    const ctx = await requireJournalAccess(req, res);
    if (!ctx) return;

    const readiness = await getPantryReadiness(ctx.personId);
    return res.status(200).json({ readiness });
  } catch (err) {
    console.error('[API /journal/plans/pantry/readiness] error:', err);
    return res.status(500).json({ error: 'Internal server error' });
  }
}
