import type { ModuleFieldDescriptorMap } from './fieldDescriptors';

export const PROGRAM_COLLECTIONS_RAIL_FIELD_DESCRIPTORS: ModuleFieldDescriptorMap = {
  'grid.program-collections-rail.v1': [
    {
      key: 'heading',
      label: 'Section heading',
      type: 'textarea',
      optional: true,
      placeholder: 'Begin with nutrition, then follow your signals',
      hint: 'Leave blank to use the default Programs rail heading.',
    },
    {
      key: 'intro',
      label: 'Intro copy',
      type: 'textarea',
      optional: true,
      placeholder: 'Each pathway is a public overview. Active enrollment and delivery live in the signed-in app.',
    },
    {
      key: 'collectionSlugs',
      label: 'Collection slugs',
      type: 'string-list',
      optional: true,
      placeholder: 'nutrition',
      hint: 'Optional ordered filter. Leave empty to render all published Program Collections from the catalogue.',
    },
    {
      key: 'featuredCollectionSlug',
      label: 'Featured collection slug',
      type: 'text',
      optional: true,
      placeholder: 'nutrition',
      hint: 'Controls the wide CTA beneath the rail. Defaults to nutrition.',
    },
    {
      key: 'featuredEyebrow',
      label: 'Featured card eyebrow',
      type: 'text',
      optional: true,
      placeholder: 'Start here',
      group: 'Card labels',
    },
    {
      key: 'secondaryEyebrow',
      label: 'Other card eyebrow',
      type: 'text',
      optional: true,
      placeholder: 'Coming soon',
      group: 'Card labels',
    },
    {
      key: 'ctaNote',
      label: 'Wide CTA note',
      type: 'textarea',
      optional: true,
      placeholder: 'Start with Baseline in Nutrition Foundations — the featured pathway most members begin with.',
      group: 'CTA',
    },
    {
      key: 'showFeaturedCta',
      label: 'Show wide CTA under rail',
      type: 'boolean',
      optional: true,
      group: 'CTA',
      hint: 'Defaults to on. CTA label/link resolve from the featured Program Collection.',
    },
    {
      key: 'cards',
      label: 'Authored cards (overrides catalogue)',
      type: 'object-list',
      optional: true,
      group: 'Authored cards',
      collapsedByDefault: true,
      hint: 'When this list has items, the rail renders these authored cards instead of the resolver catalogue. Leave empty to keep the Programs catalogue rail.',
      fields: [
        { key: 'id', label: 'Card id', type: 'text', optional: true, placeholder: 'pathway-card-1' },
        { key: 'eyebrow', label: 'Eyebrow', type: 'text', optional: true, placeholder: 'Start here' },
        { key: 'title', label: 'Headline', type: 'text', placeholder: 'Nutrition Foundations' },
        {
          key: 'priceLine',
          label: 'Price line',
          type: 'text',
          optional: true,
          placeholder: 'From $425',
          hint: 'Renders directly under the headline using the same visual treatment.',
        },
        { key: 'description', label: 'Description', type: 'textarea', optional: true },
        { key: 'image', label: 'Image', type: 'image-url', optional: true, placeholder: '/images/...' },
        { key: 'imageAlt', label: 'Image alt text', type: 'text', optional: true },
        { key: 'ctaLabel', label: 'CTA label', type: 'text', optional: true, placeholder: 'Explore the pathway' },
        { key: 'ctaHref', label: 'CTA link', type: 'url', optional: true, placeholder: '/integrative-care#programs' },
        {
          key: 'showNote',
          label: 'Show note under CTA',
          type: 'boolean',
          optional: true,
        },
        {
          key: 'note',
          label: 'Note',
          type: 'textarea',
          optional: true,
          hint: 'Center-aligned, xs, wraps naturally. Renders only when "Show note under CTA" is on and this field is non-empty.',
        },
      ],
    },
  ],
};
