/**
 * Public Pathway Module Catalog
 *
 * Style-guide catalog entries for runtime modules used by Programs,
 * Integrative Care, Start/Launch, and offer/pathway pages. These entries make
 * existing runtime modules discoverable without merging registries.
 */

import type { ModuleDefinition } from '@/lib/moduleRegistry';

function moduleProps(options: {
  backgroundType?: ModuleDefinition['properties']['backgroundType'];
  headlineSize?: string;
  bodySize?: string;
  textAlignment?: 'center' | 'left';
  contentPosition?: ModuleDefinition['properties']['contentPosition'];
  cornerRadius?: string;
  maxWidth?: string;
  height?: string;
  hasOverlay?: boolean;
  hasButtons?: boolean;
  buttonVariants?: string[];
  responsiveNotes?: string;
}): ModuleDefinition['properties'] {
  return {
    backgroundType: options.backgroundType ?? ['solid'],
    headlineSize: options.headlineSize ?? '2xl–5xl depending on module',
    headlineWeight: 'font-semibold (600)',
    bodySize: options.bodySize ?? 'sm/base',
    bodyWeight: 'font-light / regular depending on module',
    textAlignment: options.textAlignment ?? 'left',
    contentPosition: options.contentPosition ?? 'top-left',
    cornerRadius: options.cornerRadius ?? 'module-defined rounded cards / bands',
    maxWidth: options.maxWidth ?? 'section container',
    height: options.height ?? 'content-driven',
    responsiveNotes: options.responsiveNotes ?? 'Responsive section module; exact behavior owned by runtime component.',
    hasOverlay: options.hasOverlay ?? false,
    hasButtons: options.hasButtons ?? false,
    buttonVariants: options.buttonVariants,
    isContentDriven: true,
  };
}

export const PUBLIC_PATHWAY_MODULE_STYLE_CATALOG: ModuleDefinition[] = [
  {
    slug: 'hero-offer-blur-v1',
    name: 'Hero Offer Blur V1',
    description:
      'Runtime hero for public pathway and offer pages. Image-backed hero with blur/overlay treatment, title, subtitle, and primary CTA.',
    componentPath: '@/components/modules/HeroOfferBlurV1',
    category: 'hero',
    usedOn: ['/integrative-care/[productSlug]', '/start/[slug]', '/programs/[categorySlug]'],
    theme: 'dark',
    properties: moduleProps({
      backgroundType: ['image', 'blur'],
      textAlignment: 'center',
      contentPosition: 'center',
      height: 'large hero / content-driven',
      hasOverlay: true,
      hasButtons: true,
      buttonVariants: ['primary'],
      responsiveNotes: 'Uses responsive image fields and overlay strength controlled by module content.',
    }),
    variants: ['default', 'dark-overlay'],
    status: 'stable',
    lifecycle: 'approved',
    surface: 'public_site',
    reusability: 'needs_data',
    editableFields: { copy: true, images: true, buttons: true },
    dataContract: {
      contentSource: 'runtime composition JSON → hero.offer-blur.v1',
      requiredProps: ['title', 'subtitle', 'ctaLabel', 'ctaHref'],
      optionalProps: ['imageDesktop', 'imageMobile', 'overlayStrength'],
      fallbackStates: ['ready'],
    },
    governance: { cmsEditable: true, developerOwned: true },
  },
  {
    slug: 'process-slide-stack-v1',
    name: 'Process Slide Stack V1',
    description:
      'Step-by-step process module with stacked slides/images. Used to explain practitioner-supported or guided pathway flows.',
    componentPath: '@/components/modules/ProcessSlideStackV1',
    category: 'content',
    usedOn: ['/integrative-care/[productSlug]'],
    theme: 'both',
    properties: moduleProps({
      backgroundType: ['solid', 'image'],
      headlineSize: '3xl–5xl',
      hasButtons: false,
      responsiveNotes: 'Steps stack responsively; each step may carry image fields and list lines.',
    }),
    variants: ['4-step-process', 'image-backed-steps'],
    status: 'stable',
    lifecycle: 'approved',
    surface: 'public_site',
    reusability: 'needs_data',
    editableFields: { copy: true, images: true },
    dataContract: {
      contentSource: 'runtime composition JSON → process.slide-stack.v1',
      requiredProps: ['heading', 'steps[]'],
      optionalProps: ['defaultOpenIndex'],
      fallbackStates: ['ready'],
    },
    governance: { cmsEditable: true, developerOwned: true },
  },
  {
    slug: 'process-timed-steps-v1',
    name: 'Process Timed Steps V1',
    description:
      'Timed/clickable how-it-works module for program category and Start pages. Useful when the page needs lightweight sequential education.',
    componentPath: '@/components/modules/ProcessTimedStepsV1',
    category: 'content',
    usedOn: ['/programs/[categorySlug]', '/start/[slug]'],
    theme: 'both',
    properties: moduleProps({
      backgroundType: ['solid'],
      headlineSize: '2xl–4xl',
      responsiveNotes: 'Auto-advancing steps with reduced-motion-safe behavior owned by component.',
    }),
    variants: ['auto-highlight', 'clickable-steps'],
    status: 'stable',
    lifecycle: 'approved',
    surface: 'public_site',
    reusability: 'needs_data',
    editableFields: { copy: true },
    dataContract: {
      contentSource: 'runtime composition JSON → process.timed-steps.v1',
      requiredProps: ['heading', 'steps[]'],
      optionalProps: ['intervalMs'],
      fallbackStates: ['ready'],
    },
    governance: { cmsEditable: true, developerOwned: true },
  },
  {
    slug: 'persuasion-simple-cta-v1',
    name: 'Persuasion Simple CTA V1',
    description:
      'Flexible persuasion block for lists, paragraphs, and final decision support. Often used between process/proof sections and final CTAs.',
    componentPath: '@/components/modules/PersuasionSimpleCtaV1',
    category: 'cta',
    usedOn: ['/integrative-care/[productSlug]', '/programs', '/start/[slug]'],
    theme: 'both',
    properties: moduleProps({
      backgroundType: ['solid'],
      headlineSize: '2xl–4xl',
      hasButtons: true,
      buttonVariants: ['primary'],
    }),
    variants: ['list', 'paragraph'],
    status: 'stable',
    lifecycle: 'approved',
    surface: 'public_site',
    reusability: 'needs_data',
    editableFields: { copy: true, buttons: true },
    dataContract: {
      contentSource: 'runtime composition JSON → persuasion.simple-cta.v1',
      requiredProps: ['heading'],
      optionalProps: ['intro', 'items[]', 'bodyParagraphs[]', 'ctaLabel', 'ctaHref', 'variant'],
      fallbackStates: ['ready'],
    },
    governance: { cmsEditable: true, developerOwned: true },
  },
  {
    slug: 'ambient-marquee-strip-v1',
    name: 'Ambient Marquee Strip V1',
    description:
      'Animated message strip for emotional emphasis or brand rhythm between larger modules.',
    componentPath: '@/components/modules/AmbientMarqueeStripV1',
    category: 'ambient',
    usedOn: ['/integrative-care/[productSlug]', '/start/[slug]'],
    theme: 'dark',
    properties: moduleProps({
      backgroundType: ['solid'],
      headlineSize: 'ticker text',
      textAlignment: 'center',
      contentPosition: 'center',
      height: 'compact strip',
      responsiveNotes: 'Animated marquee with speed/direction/pause controls.',
    }),
    variants: ['left', 'right', 'pause-on-hover'],
    status: 'stable',
    lifecycle: 'approved',
    surface: 'public_site',
    reusability: 'needs_data',
    editableFields: { copy: true },
    dataContract: {
      contentSource: 'runtime composition JSON → ambient.marquee-strip.v1',
      requiredProps: ['text'],
      optionalProps: ['speed', 'direction', 'pauseOnHover'],
      fallbackStates: ['ready'],
    },
    governance: { cmsEditable: true, developerOwned: true },
  },
  {
    slug: 'case-study-scroll-cards-v1',
    name: 'Case Study Scroll Cards V1',
    description:
      'Horizontally scrolling proof/story card module for pathways, featured programs, and client case studies.',
    componentPath: '@/components/modules/CaseStudyScrollCardsV1',
    category: 'card',
    usedOn: ['/integrative-care/[productSlug]', '/programs'],
    theme: 'both',
    properties: moduleProps({
      backgroundType: ['image', 'solid'],
      headlineSize: 'section heading + card copy',
      cornerRadius: 'rounded cards',
      responsiveNotes: 'Scrollable card rail with responsive image fields.',
    }),
    variants: ['case-studies', 'featured-pathways'],
    status: 'stable',
    lifecycle: 'approved',
    surface: 'public_site',
    reusability: 'needs_data',
    editableFields: { copy: true, images: true },
    dataContract: {
      contentSource: 'runtime composition JSON → case-study.scroll-cards.v1',
      requiredProps: ['cards[]'],
      optionalProps: ['sectionHeading'],
      fallbackStates: ['ready', 'empty'],
    },
    governance: { cmsEditable: true, developerOwned: true },
  },
  {
    slug: 'faq-accordion-v2',
    name: 'FAQ Accordion V2',
    description:
      'Approved pathway FAQ accordion for Programs, Integrative Care, and Start pages.',
    componentPath: '@/components/modules/FaqAccordionV2',
    category: 'content',
    usedOn: ['/integrative-care/[productSlug]', '/programs', '/start/[slug]'],
    theme: 'both',
    properties: moduleProps({
      backgroundType: ['solid'],
      headlineSize: 'section title + question rows',
      responsiveNotes: 'Accordion rows stack responsively; default open index is content-driven.',
    }),
    variants: ['default-open', 'all-closed'],
    status: 'stable',
    lifecycle: 'approved',
    surface: 'public_site',
    reusability: 'needs_data',
    editableFields: { copy: true },
    dataContract: {
      contentSource: 'runtime composition JSON → faq.accordion.v2',
      requiredProps: ['items[]'],
      optionalProps: ['title', 'defaultOpenIndex'],
      fallbackStates: ['ready', 'empty'],
    },
    governance: { cmsEditable: true, developerOwned: true },
  },
  {
    slug: 'feature-reasons-split-v1',
    name: 'Feature Reasons Split V1',
    description:
      'Split feature module pairing an image with numbered reasons or differentiators.',
    componentPath: '@/components/modules/FeatureReasonsSplitV1',
    category: 'content',
    usedOn: ['/integrative-care/[productSlug]', '/programs/[categorySlug]'],
    theme: 'both',
    properties: moduleProps({
      backgroundType: ['image', 'solid'],
      headlineSize: '3xl–5xl',
      responsiveNotes: 'Image/text split stacks on smaller screens.',
    }),
    variants: ['three-reasons', 'differentiator-strip'],
    status: 'stable',
    lifecycle: 'approved',
    surface: 'public_site',
    reusability: 'needs_data',
    editableFields: { copy: true, images: true },
    dataContract: {
      contentSource: 'runtime composition JSON → feature.reasons-split.v1',
      requiredProps: ['heading', 'items[]'],
      optionalProps: ['imageDesktop', 'imageMobile', 'imageAlt'],
      fallbackStates: ['ready'],
    },
    governance: { cmsEditable: true, developerOwned: true },
  },
  {
    slug: 'cta-program-offer-v1',
    name: 'Program Offer CTA V1',
    description:
      'Program-specific conversion CTA that routes users toward a program offer, account creation, or next step.',
    componentPath: '@/components/modules/CtaProgramOfferV1',
    category: 'cta',
    usedOn: ['/programs', '/programs/[categorySlug]'],
    theme: 'both',
    properties: moduleProps({
      backgroundType: ['solid'],
      headlineSize: '2xl–4xl',
      hasButtons: true,
      buttonVariants: ['primary'],
    }),
    variants: ['primary-offer', 'coming-soon-safe'],
    status: 'stable',
    lifecycle: 'approved',
    surface: 'public_site',
    reusability: 'needs_data',
    editableFields: { copy: true, buttons: true },
    dataContract: {
      contentSource: 'runtime composition JSON → cta.program-offer.v1',
      requiredProps: ['heading', 'ctaLabel', 'ctaHref'],
      optionalProps: ['body', 'microcopy'],
      fallbackStates: ['ready'],
    },
    governance: { cmsEditable: true, developerOwned: true },
  },
  {
    slug: 'comparison-table-v1',
    name: 'Comparison Table V1',
    description:
      'Comparison module for explaining differences across programs, support levels, app access, or service options.',
    componentPath: '@/components/modules/ComparisonTableV1',
    category: 'grid',
    usedOn: ['/programs', '/programs/[categorySlug]', '/start/[slug]'],
    theme: 'both',
    properties: moduleProps({
      backgroundType: ['solid'],
      headlineSize: 'section heading + table cells',
      responsiveNotes: 'Table/card behavior is runtime-owned for smaller screens.',
    }),
    variants: ['program-comparison', 'support-levels'],
    status: 'stable',
    lifecycle: 'approved',
    surface: 'public_site',
    reusability: 'needs_data',
    editableFields: { copy: true },
    dataContract: {
      contentSource: 'runtime composition JSON → comparison.table.v1',
      requiredProps: ['columns[]', 'rows[]'],
      optionalProps: ['heading', 'subheading'],
      fallbackStates: ['ready', 'empty'],
    },
    governance: { cmsEditable: true, developerOwned: true },
  },
  {
    slug: 'feature-icon-tiles-v1',
    name: 'Feature Icon Tiles V1',
    description:
      'Tile grid for differentiators, benefits, app capabilities, or program pillars.',
    componentPath: '@/components/modules/FeatureIconTilesV1',
    category: 'grid',
    usedOn: ['/programs', '/programs/[categorySlug]', '/start/[slug]'],
    theme: 'both',
    properties: moduleProps({
      backgroundType: ['solid'],
      headlineSize: 'section heading + tile labels',
      responsiveNotes: 'Responsive tile grid; icons/content are driven by runtime JSON.',
    }),
    variants: ['benefit-tiles', 'app-capabilities'],
    status: 'stable',
    lifecycle: 'approved',
    surface: 'public_site',
    reusability: 'needs_data',
    editableFields: { copy: true },
    dataContract: {
      contentSource: 'runtime composition JSON → feature.icon-tiles.v1',
      requiredProps: ['items[]'],
      optionalProps: ['heading', 'subheading'],
      fallbackStates: ['ready', 'empty'],
    },
    governance: { cmsEditable: true, developerOwned: true },
  },
  {
    slug: 'grid-program-cards-v1',
    name: 'Program Card Grid V1',
    description:
      'Program card grid for public Programs index/category pages. Presents available and coming-soon programs with centralized CTA behavior.',
    componentPath: '@/components/modules/GridProgramCardsV1',
    category: 'grid',
    usedOn: ['/programs', '/programs/[categorySlug]'],
    theme: 'both',
    properties: moduleProps({
      backgroundType: ['solid', 'image'],
      headlineSize: 'card headings + metadata',
      cornerRadius: 'rounded cards',
      hasButtons: true,
      buttonVariants: ['primary', 'secondary'],
      responsiveNotes: 'Responsive card grid with optional image/fallback behavior.',
    }),
    variants: ['programs-index', 'category-grid', 'coming-soon'],
    status: 'stable',
    lifecycle: 'approved',
    surface: 'public_site',
    reusability: 'needs_data',
    editableFields: { copy: true, images: true, buttons: true },
    dataContract: {
      contentSource: 'runtime composition JSON / Programs marketing data → grid.program-cards.v1',
      requiredProps: ['cards[]'],
      optionalProps: ['heading', 'subheading'],
      fallbackStates: ['ready', 'empty'],
    },
    governance: {
      cmsEditable: true,
      developerOwned: true,
      safetyNotes: ['CTA behavior should remain centralized; do not let metadata invent enrollment/progress truth.'],
    },
  },
  {
    slug: 'nav-program-pathway-v1',
    name: 'Program Pathway Nav V1',
    description:
      'Navigation module for Programs/pathway pages. Helps users move across program categories or pathway sections.',
    componentPath: '@/components/modules/NavProgramPathwayV1',
    category: 'navigation',
    usedOn: ['/programs', '/programs/[categorySlug]'],
    theme: 'both',
    properties: moduleProps({
      backgroundType: ['solid'],
      headlineSize: 'nav labels',
      height: 'compact nav band',
      responsiveNotes: 'Responsive pathway navigation; routing/link rules remain developer-owned.',
    }),
    variants: ['category-nav', 'section-anchor-nav'],
    status: 'stable',
    lifecycle: 'approved',
    surface: 'public_site',
    reusability: 'needs_data',
    editableFields: { copy: true },
    dataContract: {
      contentSource: 'runtime composition JSON → nav.program-pathway.v1',
      requiredProps: ['items[]'],
      optionalProps: ['activeItem'],
      fallbackStates: ['ready', 'empty'],
    },
    governance: { cmsEditable: true, developerOwned: true },
  },
  {
    slug: 'pricing-tiers-v1',
    name: 'Pricing Tiers V1',
    description:
      'Pricing/options module for public purchase, Start, or offer-entry pages. Presentation only; billing truth remains in offers/price options.',
    componentPath: '@/components/modules/PricingTiersV1',
    category: 'cta',
    usedOn: ['/start/[slug]', '/buy/[offerKey]'],
    theme: 'both',
    properties: moduleProps({
      backgroundType: ['solid'],
      headlineSize: 'pricing card headings',
      hasButtons: true,
      buttonVariants: ['primary'],
      responsiveNotes: 'Pricing cards stack responsively; price IDs and billing rules are not owned by module metadata.',
    }),
    variants: ['single-tier', 'multi-tier', 'featured-tier'],
    status: 'stable',
    lifecycle: 'approved',
    surface: 'public_site',
    reusability: 'needs_data',
    editableFields: { copy: true, buttons: true },
    dataContract: {
      contentSource: 'runtime composition JSON / Start Page pricing DTO → pricing.tiers.v1',
      requiredProps: ['tiers[]'],
      optionalProps: ['heading', 'subheading'],
      fallbackStates: ['ready', 'empty'],
    },
    governance: {
      cmsEditable: true,
      developerOwned: true,
      safetyNotes: ['Billing truth, Stripe price IDs, trials, and entitlements must stay outside module metadata.'],
    },
  },
];
